--- #YAML:1.0
name: CGI-Application-Plugin-Config-General
version: 0.07
author:
  - Michael Graham <mag-perl@occamstoothbrush.com>
abstract: Add Config::General Support to CGI::Application
license: perl
requires:
  CGI::Application: 0
  Config::General::Match: 0
  Scalar::Util: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::Config::General:
    file: lib/CGI/Application/Plugin/Config/General.pm
    version: 0.07
generated_by: Module::Build version 0.2607
